### ISSUE TITLE
Laravel 8 Upgrade

### ISSUE THREAD

**Issue by MichaelHoughton** [maxacarvalho/livewire-surge#4]
Hey Calab,

A really amazing job on Livewire and Surge.  I've been programming 16 years, and Livewire is something which is out of this world - thank you!

I wanted to check if you would be willing to accept a PR to upgrade Surge to Laravel 8?  I am happy to handle the change, just wanted to make sure it wasn't something you had thought about already.

Thanks
Michael

**Comment by ju5t** [comment]
@MichaelHoughton this isn't the official repository. It's a copy (not even a fork).

@maxacarvalho, I'm sure this is a mistake, but please remove this repository. Both @calebporzio and the guys of @tailwindlabs (cc @adamwathan) put a lot of hard work and effort in what they do, not to find such things copied in the public for people who may not own the proper licensing.

**Comment by MichaelHoughton** [comment]
Thanks @ju5t
